# DNS redirect 53 → 53 sur dnscrypt (interfaces physiques et VPN uniquement)
# lo0 exclu — dnscrypt écoute directement sur 127.0.0.1:53
rdr pass on { en0, en1, en2, en3 }         proto { udp, tcp } from any to any port 53 -> 127.0.0.1 port 53
rdr pass on { utun0, utun1, utun2, utun3 } proto { udp, tcp } from any to any port 53 -> 127.0.0.1 port 53

